#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=48:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=8   # 8 processor core(s) per node
#SBATCH --mem=122G   # maximum memory per node
#SBATCH --gres=gpu:a100:1
#SBATCH --job-name="02_blastdb_embeddings"
#SBATCH --mail-user=parnal@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

conda deactivate
export PYTHONPATH='/work/idoerg/parnal/.local/lib/python3.9/'
python prott5_embedder.py --input final_blast_db_seqs.fasta --output embeddings/blast_db_embeddings.h5 --per_protein 1 --model '/work/idoerg/parnal/.cache/huggingface/'
